[versions]
gmp = '2.0.0'
annotations = '26.0.2'
bootstrap = '1.1'
joptsimple = '6.0-alpha-3'
groovy = '5.0.3'
gson = '2.13.2'
biweekly = '0.6.8'
xjc-gp = '1.9.0'
jakarta-xml-bind = '4.0.4'
jakarta-activation = '2.1.4'
glassfish-jaxb = '4.0.6'
google-client-api = '2.8.1'
google-client-oauth = '1.39.0'
google-apis-calendar = 'v3-rev20251207-2.0.0'
google-apis-people = 'v1-rev20251117-2.0.0'
jupiter = '6.0.2'

[plugins]
gmp = { id = 'org.javamodularity.moduleplugin', version.ref = 'gmp' }
bootstrap = { id = 'eu.tuxtown.bootstrap.gradle', version.ref = 'bootstrap' }
xjc = { id = 'com.github.bjornvester.xjc', version.ref = 'xjc-gp' }

[libraries]
annotations = { module = 'org.jetbrains:annotations', version.ref = 'annotations' }
launcher = { module = 'eu.tuxtown.bootstrap:launcher', version.ref = 'bootstrap' }
joptsimple = { module = 'net.sf.jopt-simple:jopt-simple', version.ref = 'joptsimple' }
groovy = { module = 'org.apache.groovy:groovy', version.ref = 'groovy' }
gson = { module = 'com.google.code.gson:gson', version.ref = 'gson' }
biweekly = { module = 'net.sf.biweekly:biweekly', version.ref = 'biweekly' }
jakarta-xml-bind = { module = 'jakarta.xml.bind:jakarta.xml.bind-api', version.ref = 'jakarta-xml-bind' }
jakarta-activation = { module = 'jakarta.activation:jakarta.activation-api', version.ref = 'jakarta-activation' }
glassfish-jaxb-xjc = { module = 'org.glassfish.jaxb:jaxb-xjc', version.ref = 'glassfish-jaxb' }
glassfish-jaxb-runtime = { module = 'org.glassfish.jaxb:jaxb-runtime', version.ref = 'glassfish-jaxb' }
google-client-api = { module = 'com.google.api-client:google-api-client', version.ref = 'google-client-api' }
google-client-oauth = { module = 'com.google.oauth-client:google-oauth-client', version.ref = 'google-client-oauth' }
google-client-oauth-jetty = { module = 'com.google.oauth-client:google-oauth-client-jetty', version.ref = 'google-client-oauth' }
google-apis-calendar = { module = 'com.google.apis:google-api-services-calendar', version.ref = 'google-apis-calendar' }
google-apis-people = { module = 'com.google.apis:google-api-services-people', version.ref = 'google-apis-people' }
jupiter = { module = 'org.junit.jupiter:junit-jupiter', version.ref = 'jupiter' }
jupiter-engine = { module = 'org.junit.jupiter:junit-jupiter-engine', version.ref = 'jupiter' }
jupiter-launcher = { module = 'org.junit.platform:junit-platform-launcher', version.ref = 'jupiter' }
