[versions]
gmp = '1.8.15'
annotations = '26.0.2'
bootstrap = '1.0'
joptsimple = '6.0-alpha-3'
groovy = '4.0.28'
gson = '2.13.1'
biweekly = '0.6.8'
xjc-gp = '1.8.2'
jakarta-xml-bind = '4.0.2'
jakarta-activation = '2.1.3'
glassfish-jaxb = '4.0.6'
google-client-api = '2.8.1'
google-client-oauth = '1.39.0'
google-apis-calendar = 'v3-rev20250404-2.0.0'
google-apis-people = 'v1-rev20250513-2.0.0'
jupiter = '5.12.1'

[plugins]
gmp = { id = 'org.javamodularity.moduleplugin', version.ref = 'gmp' }
bootstrap = { id = 'eu.tuxtown.bootstrap.gradle', version.ref = 'bootstrap' }
xjc = { id = 'com.github.bjornvester.xjc', version.ref = 'xjc-gp' }

[libraries]
annotations = { module = 'org.jetbrains:annotations', version.ref = 'annotations' }
launcher = { module = 'eu.tuxtown.bootstrap:launcher', version.ref = 'bootstrap' }
joptsimple = { module = 'net.sf.jopt-simple:jopt-simple', version.ref = 'joptsimple' }
groovy = { module = 'org.apache.groovy:groovy', version.ref = 'groovy' }
gson = { module = 'com.google.code.gson:gson', version.ref = 'gson' }
biweekly = { module = 'net.sf.biweekly:biweekly', version.ref = 'biweekly' }
jakarta_xml_bind = { module = 'jakarta.xml.bind:jakarta.xml.bind-api', version.ref = 'jakarta-xml-bind' }
jakarta_activation = { module = 'jakarta.activation:jakarta.activation-api', version.ref = 'jakarta-activation' }
glassfish_jaxb_xjc = { module = 'org.glassfish.jaxb:jaxb-xjc', version.ref = 'glassfish-jaxb' }
glassfish_jaxb_runtime = { module = 'org.glassfish.jaxb:jaxb-runtime', version.ref = 'glassfish-jaxb' }
google_client_api = { module = 'com.google.api-client:google-api-client', version.ref = 'google-client-api' }
google_client_oauth = { module = 'com.google.oauth-client:google-oauth-client', version.ref = 'google-client-oauth' }
google_client_oauth_jetty = { module = 'com.google.oauth-client:google-oauth-client-jetty', version.ref = 'google-client-oauth' }
google_apis_calendar = { module = 'com.google.apis:google-api-services-calendar', version.ref = 'google-apis-calendar' }
google_apis_people = { module = 'com.google.apis:google-api-services-people', version.ref = 'google-apis-people' }
jupiter = { module = 'org.junit.jupiter:junit-jupiter', version.ref = 'jupiter' }
jupiter_runtime = { module = 'org.junit.platform:junit-platform-launcher' }
