name: 'Deploy'

on:
  create:
    branches:
      - 'master'

jobs:
  deploy:
    if: startsWith(github.repository, 'noeppi-noeppi/') && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: 'Setup Java'
        uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: 'Build Crocus'
        run: |
          ./gradlew \
          -Pversion=${{ github.ref_name }} \
          -PtuxtownUsername=${{ secrets.PUBLISH_USER }} \
          -PtuxtownPassword=${{ secrets.PUBLISH_PASSWORD }} \
          build publish

      - name: 'Release Crocus'
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          body: "Crocus ${{ github.ref_name }}"
          name: "v${{ github.ref_name }}"
          tag_name: "${{ github.ref_name }}"
          files: |
            core/build/distributions/*

      - name: 'Install Python'
        run: sudo apt-get install -y python3 python3-pip pipenv

      - name: 'Install Dependencies'
        working-directory: docs
        run: pipenv install --deploy

      - name: 'Build Documentation'
        working-directory: docs
        run: pipenv run mkdocs build

      - name: 'Deploy Documentation'
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: gh-pages
          folder: 'docs/site'
          clean: true
          git-config-name: 'Github Actions'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
